"""
Verdict explainer — the Phase 2 AI layer.

Takes a MatchResult (the deterministic output from fit_scorer.py) and
produces a 2-3 sentence plain-English explanation of WHY the score is
what it is. The LLM never computes or invents the percentage — it only
explains a number that was already computed by ordinary code.

Same dual-engine pattern as the roadmap generator:
  - GroqVerdictExplainer  — LLM-generated, natural-sounding
  - TemplateVerdictExplainer — deterministic fallback, always available

Design decisions:

1. WHY feed structured data, not raw text?
   The LLM receives the already-computed matched/missing/unmatched lists,
   not the raw resume or listing text. This means it can't hallucinate
   skills that weren't actually extracted, and it can't contradict the
   score — it's explaining a fact, not forming an opinion.

2. WHY force short output (max_tokens=300)?
   The feature plan says "one verdict, one or two sentences of why."
   A 300-token cap physically prevents the LLM from rambling into a
   full career-coaching essay, which would undermine the "simple to
   understand" requirement.

3. WHY the verdict label is NOT generated by the LLM?
   Consistency. "Strong Fit" / "Good Fit" / "Partial Fit" / "Needs Work"
   is a fixed vocabulary from the scorer. The LLM writes the explanation
   paragraph, but the headline label is always the deterministic one —
   so a student checking three listings sees the same label system every
   time, not three different phrasings.
"""

from __future__ import annotations

import os
import re

import requests

from core.match.fit_scorer import MatchResult

GROQ_URL = "https://api.groq.com/openai/v1/chat/completions"
GROQ_MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = """You are a placement advisor at an Indian engineering college. \
You explain role-fit scores to students in 2-3 sentences. Be honest, specific, \
and encouraging where warranted. Never invent skills or contradict the data given. \
Do NOT restate the percentage or verdict label — the UI already shows those. \
Write only the explanation paragraph, nothing else."""

USER_PROMPT_TEMPLATE = """The student is checking their fit for: {title} at {company}.

Score: {match_pct}% ({verdict})
Skills they HAVE that the role wants: {matched}
Skills the role wants that they're MISSING: {missing}
Tags from the listing that aren't real technical skills: {unmatched}
Academic marks used: {marks} (contributed {acad_adj:+.1f} points to the score)

Write a 2-3 sentence explanation of this result for the student. Be specific about \
which matched skills are their strength for this role, which missing skills matter \
most, and whether the unmatched tags (soft-skill phrasing) are worth worrying about. \
Keep it under 60 words."""


class GroqVerdictExplainer:
    def __init__(self, api_key: str | None = None, timeout: int = 20):
        self.api_key = api_key or os.environ.get("GROQ_API_KEY", "")
        self.timeout = timeout

    @property
    def available(self) -> bool:
        return bool(self.api_key)

    def explain(self, result: MatchResult) -> str:
        prompt = USER_PROMPT_TEMPLATE.format(
            title=result.listing_title,
            company=result.company,
            match_pct=result.match_pct,
            verdict=result.verdict,
            matched=", ".join(result.matched_skills) or "none",
            missing=", ".join(result.missing_skills) or "none",
            unmatched=", ".join(result.unmatched_tags) or "none",
            marks=", ".join(f"{m}%" for m in result.academic_marks_used) or "not provided",
            acad_adj=result.academic_adjustment,
        )
        resp = requests.post(
            GROQ_URL,
            headers={"Authorization": f"Bearer {self.api_key}",
                     "Content-Type": "application/json"},
            json={
                "model": GROQ_MODEL,
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt},
                ],
                "temperature": 0.3,
                "max_tokens": 300,
            },
            timeout=self.timeout,
        )
        resp.raise_for_status()
        return resp.json()["choices"][0]["message"]["content"].strip()


class TemplateVerdictExplainer:
    """Deterministic fallback — always available, no API needed."""

    def explain(self, result: MatchResult) -> str:
        parts = []

        if result.matched_skills:
            top = ", ".join(result.matched_skills[:3])
            parts.append(f"Your {top} skills align well with what this role asks for.")

        if result.missing_skills:
            top_miss = ", ".join(result.missing_skills[:3])
            if len(result.missing_skills) > 3:
                parts.append(f"The main gaps are {top_miss} and {len(result.missing_skills) - 3} more.")
            else:
                parts.append(f"The gaps to close are {top_miss}.")

        if result.unmatched_tags:
            parts.append(
                f"The listing also mentions {', '.join(result.unmatched_tags[:2])}, "
                f"which are general traits rather than specific technical skills."
            )

        if not result.matched_skills and not result.missing_skills:
            parts.append(
                "This listing didn't specify clear technical skills, "
                "so the match is based on general profile context only."
            )

        return " ".join(parts)


def explain_verdict(
    result: MatchResult,
    api_key: str | None = None,
) -> str:
    """Try Groq, fall back to template — same pattern as roadmap generation."""
    groq = GroqVerdictExplainer(api_key=api_key)
    if groq.available:
        try:
            return groq.explain(result)
        except Exception:
            pass
    return TemplateVerdictExplainer().explain(result)
